config/routes.rb
Rails.application.routes.draw do
  root 'magic_light#index', as: 'magic_light'

  resource :lights do
    collection do
      get 'turnoffall'
      get 'turnonall'
    end
  end

  resources :lights do
    member do
      get :turnon
      get :turnoff
    end
  end

  resources :colors do
    collection do
      get 'warmwhite'
    end
  end

end

app/models/color.rb
require 'socket'

class Color < ActiveRecord::Base
  belongs_to :light

  validates_format_of :color, with: /\A#?(?:[A-F0-9]{3}){1,2}\z/i
  #validates_presence_of :color

  def self.changecolor(light_ip, color)
    host = light_ip
    port = 5577
    if color == "#000000FF" #warmwhite
      colorstring = '31' + color.to_s[1..-1] + '0F0F' #warmwhite magic code
    else
      colorstring = '31' + color.to_s[1..-1] + '00F00F'
    end
    byteArray = [colorstring].pack 'H*'

    sumOfValues = 0
    byteArray.bytes.each do |x|
      sumOfValues += x
    end

    colorstring += (sumOfValues % (2**(byteArray.length + 1))).to_s(16)

    s = TCPSocket.new(host, port)
    s.write [colorstring].pack('H*')
    s.close
  end

  def self.getcolor(light_ip)
    host = light_ip
    port = 5577

    s = TCPSocket.new(host, port)

    s.write ["818a8b96"].pack('H*')
    color = s.read(14).unpack('H*').to_s[14...22] #read extra two to tell if its warm white 

    s.close

    if color == "000000ff" #so warm white shows as white, due to issue it shows as black
      color = "FFFFFF"
      return color
    else
      return color[0...6]
    end

  end
end

app/models/light.rb
require 'socket'

class Light < ActiveRecord::Base
  has_one :light

  validates_presence_of :ip_address
  validates_uniqueness_of :ip_address

  validates :ip_address, format: {
    with: Regexp.union(Resolv::IPv4::Regex)
  }

  def turnon(ip)
    host = ip
    port = 5577
    s = TCPSocket.new(host, port)
    s.write ["71230fa3"].pack('H*')
    s.close
  end

  def turnoff(ip)
    host = ip
    port = 5577
    s = TCPSocket.new(host, port)
    s.write ["71240fa4"].pack('H*')
    s.close
  end
end

app/models/magic_light.rb
class MagicLight < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def create
    @color = Color.all

    #@color.update_all(params[:color])
    @light = Light.all
    @light.each do |l|
      @color.changecolor(l.ip_address, params[:color][:color])
    end
    flash[:notice] = "Color changed to #{params[:color][:color]}."
    redirect_to magic_light_path
  end

  def warmwhite
    @color = Color.all

    #@color.update_all(:color => "#000000ff")
    @light = Light.all
    @light.each do |l|
      @color.changecolor(l.ip_address, "#000000FF")
    end
    flash[:notice] = "Color changed to warm white(#000000FF)."
    redirect_to magic_light_path
  end

  private

  def color_params
    params.require(:light).permit(:color, :light_id)
  end
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController
  def create
    @light = Light.new(light_params)
    @light.save
    @color = Color.new light_id: @light.id, color: '000000'
    @color.save
    if @light.save
      flash[:notice] = 'Light added successfully'
      redirect_to magic_light_path
    else
      flash[:alert] = 'Please make sure your IP is unique.'
      redirect_to magic_light_path
    end
  end

  def index
    @lights = Light.all
  end

  def turnon
    @light = Light.find(params[:id])
    @light.status = true
    @light.save
    @light.turnon(@light.ip_address)
    flash[:notice] = "Light (#{@light.ip_address}) turned on"
    redirect_to magic_light_path
  end

  def turnoff
    @light = Light.find(params[:id])
    @light.status = false
    @light.save
    @light.turnoff(@light.ip_address)
    flash[:notice] = "Light (#{@light.ip_address}) turned off"
    redirect_to magic_light_path
  end

  def turnoffall
    @light = Light.all
    @light.each do |l|
      l.status = false
      l.save
      l.turnoff(l.ip_address)
    end
    flash[:notice] = 'All Lights turned off'
    redirect_to magic_light_path
  end

  def turnonall
    @light = Light.all
    @light.each do |l|
      l.status = true
      l.save
      l.turnon(l.ip_address)
    end
    flash[:notice] = 'All Lights turned on'
    redirect_to magic_light_path
  end

  private

  def light_params
    params.require(:light).permit(:ip_address, :id)
  end
end

app/controllers/magic_light_controller.rb
class MagicLightController < ApplicationController
  def index
    @light = Light.new
    @lights = Light.all
    @color = Color.new
    # @colors = Color.all
    @colors = []

    @lights.each do |l|
      @colors.push(Color.getcolor(l.ip_address))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lights_helper.rb
module LightsHelper
end

app/views/color/_form.html.erb
<h2>
  Change Color
</h2>

<!-- <%= form_for @color do |f| %>


  <div class="field">
    HEX: <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %> -->

<!-- <%= simple_form_for @color do |f| %>
  <%= f.input :color, as: :minicolors %>
<% end %> -->

<!-- Current color: <%= @colors[0]%>  <div class="box" style ="background: <%=@colors[0]%>; float:left; margin-top: -2px"></div><br><br> -->

<%# With Bootstrap theme and swatch on the right: %>

<%= link_to "Warm White", warmwhite_colors_path%> </br>

<%= simple_form_for @color do |f| %>


<%= f.input :color, as: :minicolors, input_html: {data: {
          minicolors: {theme: :bootstrap, position: :right}}}%>
<%=   f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <ul class="nav navbar-nav"></ul>

  <p class="navbar-text navbar-left" style="margin-right: 15px;"><%= link_to "MagicLight Web", magic_light_path %></b>
</p>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MagiclightWeb</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
       <%= render 'layouts/header' %>
      <div class="row">
        <%= content_tag(:div, flash[:error], :class => "alert alert-warning") if flash[:error] %>
        <%= content_tag(:div, flash[:notice], :class => "alert alert-success") if flash[:notice] %>
        <%= content_tag(:div, flash[:alert], :class => "alert alert-danger") if flash[:alert] %>
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <div class="jumbotron"><%= yield %>
          </div>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  </body>
</html>

app/views/lights/_form.html.erb
<h2> Add a light </h2>


<%= form_for @light do |f| %>

<!-- <% if @light.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@light.errors.count, "error") %> prohibited this IP from being saved:</h2>

    <ul>
    <% @light.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> -->


  <div class="field">
    IP: <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/magic_light/index.html.erb
<h2><%= link_to "Turn On All", turnonall_lights_path %> | <%= link_to "Turn Off All", turnoffall_lights_path %></h2>



<% @lights.each_with_index do |light, index| %>
  <%= light.ip_address %> -
    <% if light.status != true %>
      <%= link_to "Turn On", turnon_light_path(light.id) %> <div class="box" style ="background: #<%=@colors[index]%>; float:left; margin-top: -2px; margin-bottom: 10px"></div></br></br>
    <% else %>
      <%= link_to "Turn Off", turnoff_light_path(light.id) %> <div class="box" style ="background: #<%=@colors[index]%>; float:left; margin-top: -2px; margin-bottom: 10px"></div></br></br>
    <%end%>
<%end%>

<%= render partial: 'lights/form', locals: { light: @light } %>
<%= render partial: 'color/form', locals: { color: @color } %>